# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-29 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='temp-slug'),
            preserve_default=False,
        ),
    ]
