# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-29 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190629_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('slug', 'pub_date')]),
        ),
    ]
